language: python
python:
  - "2.7"
sudo: false
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
      - build-essential
      - autoconf
      - automake
      - libtool
      - libreadline6-dev
      - libncurses5-dev
      - libgsl0-dev
      - python-all-dev
      - python-numpy
      - openmpi-bin
      - libopenmpi-dev
install:
  - pip install -r requirements.txt
  - pip install coverage
  - source ci/install_nest.sh
  - source ci/install_neuron.sh
  - pip install .
script:  bash ci/test_script.sh
cache:
  directories:
    - $HOME/nest-2.6.0
    - $HOME/nrn-7.4
    - $HOME/build/nest-2.6.0
    - $HOME/build/nrn-7.4
    - $HOME/build/cython
    - $HOME/.cache/pip
